name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone and checkout branch
        uses: actions/checkout@v1
      - name: Build project
        run: make
      - name: Run tests
        run: make test


  publish-pip:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone and checkout branch
        uses: actions/checkout@v1

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install twine
        run: pip install twine

      - name: Install wheel
        run: pip install wheel

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Check binaries
        run: twine check dist/*

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
